# Generated by Django 3.2.5 on 2021-07-03 22:51

import cms.fields
import cms.mixins
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', cms.fields.CharField()),
                ('slug', cms.fields.SlugField(unique=True)),
                ('number', cms.fields.PositiveIntegerField()),
                ('menu', cms.fields.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
                'ordering': ['number'],
                'abstract': False,
            },
            bases=(cms.mixins.Numbered, models.Model),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', cms.fields.CharField()),
                ('type', cms.fields.CharField()),
                ('number', cms.fields.PositiveIntegerField()),
                ('content', cms.fields.TextField()),
                ('image', cms.fields.ImageField()),
                ('video', embed_video.fields.EmbedVideoField(blank=True, help_text='Paste a YouTube, Vimeo, or SoundCloud link', verbose_name='video')),
                ('href', cms.fields.CharField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='langlevedenbosch.page')),
            ],
            options={
                'verbose_name': 'section',
                'verbose_name_plural': 'sections',
                'ordering': ['number'],
                'abstract': False,
            },
            bases=(cms.mixins.Numbered, models.Model),
        ),
        migrations.CreateModel(
            name='SectionTeaser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', cms.fields.CharField()),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='image')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                ('href', cms.fields.CharField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teasers', to='langlevedenbosch.section')),
            ],
            options={
                'ordering': ['?'],
            },
        ),
        migrations.CreateModel(
            name='SectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='langlevedenbosch.section')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='SectionCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', cms.fields.CharField()),
                ('initiative', cms.fields.CharField()),
                ('position', models.PositiveIntegerField(blank=True, verbose_name='positie')),
                ('date', cms.fields.CharField()),
                ('time', cms.fields.CharField()),
                ('subscript', cms.fields.CharField()),
                ('location', cms.fields.CharField()),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='image')),
                ('href', cms.fields.CharField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_items', to='langlevedenbosch.section')),
            ],
            options={
                'ordering': ['position'],
            },
            bases=(cms.mixins.Numbered, models.Model),
        ),
    ]
