# Generated by Django 3.0.6 on 2020-05-20 13:42

import cms.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('langlevedenbosch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionTeaser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, verbose_name='positie')),
                ('title', cms.models.VarCharField(verbose_name='titel')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='image')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                ('href', cms.models.VarCharField(blank=True, verbose_name='link')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teasers', to='langlevedenbosch.Section')),
            ],
            options={
                'ordering': ['position'],
            },
            bases=(cms.models.Numbered, models.Model),
        ),
    ]
