# Generated by Django 3.0.6 on 2020-05-27 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('langlevedenbosch', '0002_sectionteaser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionteaser',
            options={'ordering': ['?']},
        ),
        migrations.RemoveField(
            model_name='sectionteaser',
            name='position',
        ),
    ]
