# Generated by Django 3.0.6 on 2020-05-28 18:44

import cms.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('langlevedenbosch', '0003_auto_20200527_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', cms.models.VarCharField(verbose_name='titel')),
                ('initiative', cms.models.VarCharField(verbose_name='naam initiatief')),
                ('position', models.PositiveIntegerField(blank=True, verbose_name='positie')),
                ('date', cms.models.VarCharField(verbose_name='titel')),
                ('time', cms.models.VarCharField(verbose_name='titel')),
                ('subscript', cms.models.VarCharField(verbose_name='onderschrift')),
                ('location', cms.models.VarCharField(verbose_name='locatie')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='image')),
                ('href', cms.models.VarCharField(blank=True, verbose_name='link')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_items', to='langlevedenbosch.Section')),
            ],
            options={
                'ordering': ['position'],
            },
            bases=(cms.models.Numbered, models.Model),
        ),
    ]
